=== bloomreach/brxm/essentials/plugin-api/api/src/main/resources/instructions.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
  Copyright 2013 Hippo B.V. (http://www.onehippo.com)
  -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns="http://www.onehippo.org/essentials/instructions" targetNamespace="http://www.onehippo.org/essentials/instructions">
  <xs:element name="instructions" type="instructionsType"/>

  <!--
    //############################################
    // INSTRUCTION SET
    //############################################
  -->
  <xs:simpleType name="fileActionType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="delete"/>
      <xs:enumeration value="copy"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="instructionsSetType" mixed="true">
    <xs:sequence>
      <xs:element type="fileType" name="file" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element type="xmlType" name="xml" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <!--
    //############################################
    // SUBTYPES
    //############################################

  -->
  <xs:complexType name="fileType" mixed="true">
    <xs:attribute use="required" name="action" type="fileActionType" default="copy"/>
    <xs:attribute use="optional" name="source" type="xs:string"/>
    <xs:attribute use="required" name="target" type="xs:string"/>
    <xs:attribute use="optional" name="overwrite" type="xs:boolean" default="false"/>
  </xs:complexType>

  <xs:complexType name="xmlType" mixed="true">
    <xs:attribute use="required" name="action" type="fileActionType" default="copy"/>
    <xs:attribute use="optional" name="source" type="xs:string"/>
    <xs:attribute use="required" name="target" type="xs:string"/>
    <xs:attribute use="optional" name="overwrite" type="xs:boolean" default="false"/>
  </xs:complexType>


<!--  <xs:complexType name="instructionsSet" mixed="true">
    <xs:attribute use="required" name="action" type="fileActionType" default="copy"/>
    <xs:attribute use="optional" name="source" type="xs:string"/>
    <xs:attribute use="optional" name="target" type="xs:string"/>
    <xs:attribute use="optional" name="overwrite" type="xs:boolean" default="false"/>
  </xs:complexType>-->

  <!--
    //############################################
    // MAIN TYPE
    //############################################
  -->
  <xs:complexType name="instructionsType">
    <xs:all minOccurs="0" maxOccurs="1">
      <xs:element type="instructionsSetType" name="instructionSet" minOccurs="1" maxOccurs="1"/>
    </xs:all>
  </xs:complexType>

</xs:schema>

=== bloomreach/brxm/essentials/dashboard-plugins/essentials-skeleton-package/src/main/resources/META-INF/commons_instructions.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
  Copyright 2014 Hippo B.V. (http://www.onehippo.com)

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  -->

<instructions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.onehippo.org/essentials/instructions /instructions.xsd" xmlns="http://www.onehippo.org/essentials/instructions">
  <!--
  //############################################
  // COMMONS PACKAGE ADDS SHARED FILES/CONFIGURATION
  //############################################
  -->

  <instructionSet group="jsp">
    <!-- include-->
    <file action="copy" source="instructions/jsp/imports.jsp" target="{{jspRoot}}/include/imports.jsp"/>
    <file action="copy" source="instructions/jsp/pagination.jsp" target="{{jspRoot}}/include/pagination.jsp"/>
    <!-- skeleton-->
    <file action="copy" source="instructions/jsp/homepage-main-content.jsp" target="{{jspRoot}}/{{namespace}}/homepage-main-content.jsp"/>
    <file action="copy" source="instructions/jsp/base-layout.jsp" target="{{jspRoot}}/{{namespace}}/base-layout.jsp"/>
    <file action="copy" source="instructions/jsp/base-top-menu.jsp" target="{{jspRoot}}/{{namespace}}/base-top-menu.jsp"/>
    <file action="copy" source="instructions/jsp/base-footer-content.jsp" target="{{jspRoot}}/{{namespace}}/base-footer-content.jsp"/>
  </instructionSet>
  <instructionSet group="jsp">
    <xml action="copy" source="instructions/xml/hst/templates/base-layout-jsp.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
    <xml action="copy" source="instructions/xml/hst/templates/base-top-menu-jsp.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
    <xml action="copy" source="instructions/xml/hst/templates/base-footer-content-jsp.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
    <xml action="copy" source="instructions/xml/hst/templates/homepage-main-content-jsp.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
  </instructionSet>

  <instructionSet group="freemarker">
    <!-- include -->
    <file action="copy" source="instructions/freemarker/imports.ftl" target="{{freemarkerRoot}}/include/imports.ftl"/>
    <file action="copy" source="instructions/freemarker/pagination.ftl" target="{{freemarkerRoot}}/include/pagination.ftl"/>
     <!-- skeleton -->
    <file action="copy" source="instructions/freemarker/homepage-main-content.ftl" target="{{freemarkerRoot}}/{{namespace}}/homepage-main-content.ftl"/>
    <file action="copy" source="instructions/freemarker/base-layout.ftl" target="{{freemarkerRoot}}/{{namespace}}/base-layout.ftl"/>
    <file action="copy" source="instructions/freemarker/base-top-menu.ftl" target="{{freemarkerRoot}}/{{namespace}}/base-top-menu.ftl"/>
    <file action="copy" source="instructions/freemarker/base-footer-content.ftl" target="{{freemarkerRoot}}/{{namespace}}/base-footer-content.ftl"/>
  </instructionSet>
  <instructionSet group="freemarker">
    <xml action="copy" source="instructions/xml/hst/templates/base-layout-freemarker.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
    <xml action="copy" source="instructions/xml/hst/templates/base-top-menu-freemarker.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
    <xml action="copy" source="instructions/xml/hst/templates/base-footer-content-freemarker.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
    <xml action="copy" source="instructions/xml/hst/templates/homepage-main-content-freemarker.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
  </instructionSet>

  <!--
    //############################################
    // COMMON HST
    //############################################

  -->
  <instructionSet>
    <xml action="copy" source="instructions/xml/hst/workspace/base.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:workspace/hst:containers"/>
    <xml action="copy" source="instructions/xml/hst/workspace/homepage.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:workspace/hst:containers"/>
    <!-- common -->
    <xml action="copy" source="instructions/xml/hst/sitemap/root.xml" target="/hst:hst/hst:configurations/common/hst:sitemap"/>
    <xml action="copy" source="instructions/xml/hst/menu/main.xml" target="/hst:hst/hst:configurations/common/hst:sitemenus"/>

    <xml action="copy" source="instructions/xml/hst/pages/base.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:abstractpages"/>
    <xml action="copy" source="instructions/xml/hst/pages/homepage.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:pages"/>
    <!-- default-->
    <xml action="copy" source="instructions/xml/hst/catalog/essentials-catalog.xml" target="/hst:hst/hst:configurations/hst:default/hst:catalog"/>

  </instructionSet>

  <!--
  //############################################
  // CSS/JS
  //############################################
-->
  <instructionSet>
    <file binary="true" action="copy" source="instructions/js/bootstrap.min.js" target="{{javascriptRoot}}/bootstrap.min.js"/>
    <file binary="true" action="copy" source="instructions/js/jquery-2.1.0.min.js" target="{{javascriptRoot}}/jquery-2.1.0.min.js"/>
    <file action="copy" binary="true" source="instructions/bootstrap/css/bootstrap.css" target="{{siteWebRoot}}/css/bootstrap.css"/>
    <file action="copy" binary="true" source="instructions/bootstrap/css/bootstrap.min.css" target="{{siteWebRoot}}/css/bootstrap.min.css"/>
    <file action="copy" binary="true" source="instructions/bootstrap/fonts/glyphicons-halflings-regular.eot" target="{{siteWebRoot}}/fonts/glyphicons-halflings-regular.eot"/>
    <file action="copy" binary="true" source="instructions/bootstrap/fonts/glyphicons-halflings-regular.svg" target="{{siteWebRoot}}/fonts/glyphicons-halflings-regular.svg"/>
    <file action="copy" binary="true" source="instructions/bootstrap/fonts/glyphicons-halflings-regular.ttf" target="{{siteWebRoot}}/fonts/glyphicons-halflings-regular.ttf"/>
    <file action="copy" binary="true" source="instructions/bootstrap/fonts/glyphicons-halflings-regular.woff" target="{{siteWebRoot}}/fonts/glyphicons-halflings-regular.woff"/>
  </instructionSet>

</instructions>

=== bloomreach/brxm/essentials/dashboard-plugins/dashboard-events-plugin/src/main/resources/META-INF/events_package_instructions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright 2014 Hippo B.V. (http://www.onehippo.com)

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  -->


<instructions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.onehippo.org/essentials/instructions /instructions.xsd" xmlns="http://www.onehippo.org/essentials/instructions">


  <instructionSet>
    <cnd documentType="eventsdocument" superType="{{namespace}}:basedocument,hippostd:relaxed,hippotranslation:translated"/>
    <xml action="copy" source="xml/namespaces/eventsdocument.xml" target="/hippo:namespaces/{{namespace}}"/>
    <folder path="/content/documents/{{namespace}}/events/{{dateRepoYearMonth}}" template="xml/content/events.xml"/>
  </instructionSet>


  <instructionSet group="jsp">
    <file action="copy" source="jsp/eventslist-main-eventslist.jsp" target="{{jspRoot}}/hstdefault/eventslist-main-eventslist.jsp"/>
    <file action="copy" source="jsp/eventspage-main.jsp" target="{{jspRoot}}/hstdefault/eventspage-main.jsp"/>
    <xml action="copy" source="xml/hst/templates/events-main-content-jsp.xml" target="/hst:hst/hst:configurations/hst:default/hst:templates"/>
    <xml action="copy" source="xml/hst/templates/eventslist-main-eventslist-jsp.xml" target="/hst:hst/hst:configurations/hst:default/hst:templates"/>
  </instructionSet>

  <instructionSet group="freemarker">
    <freemarker action="copy" source="freemarker/eventslist-main-eventslist.ftl" target="{{freemarkerRoot}}/hstdefault/eventslist-main-eventslist.ftl"/>
    <freemarker action="copy" source="freemarker/eventspage-main.ftl" target="{{freemarkerRoot}}/hstdefault/eventspage-main.ftl"/>
    <xml action="copy" source="xml/hst/templates/events-main-content-freemarker.xml" target="/hst:hst/hst:configurations/hst:default/hst:templates"/>
    <xml action="copy" source="xml/hst/templates/eventslist-main-eventslist-freemarker.xml" target="/hst:hst/hst:configurations/hst:default/hst:templates"/>
  </instructionSet>

  <instructionSet>
    <xml action="copy" source="xml/hst/workspace/eventslist.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:workspace/hst:containers"/>
    <xml action="copy" source="xml/hst/sitemap/events.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:sitemap"/>
    <file action="copy" source="java/EventsDocument.txt" target="{{beansFolder}}/EventsDocument.java"/>
    <xml action="copy" source="xml/hst/pages/eventslist.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:pages"/>
    <xml action="copy" source="xml/hst/pages/eventspage.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:pages"/>
    <xml action="copy" source="xml/hst/catalog/eventslist.xml" target="/hst:hst/hst:configurations/hst:default/hst:catalog/essentials-catalog"/>
    <file action="copy" binary="true" source="images/component-icon-events.png" target="{{siteWebRoot}}/images/component-icon-events.png"/>
  </instructionSet>


  <!--
    //############################################
    // MENU
    //############################################
  -->
  <instructionSet>
    <xml action="copy" source="xml/hst/menu/menu-item-events.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:workspace/hst:sitemenus/main"/>
  </instructionSet>

  <!-- SAMPLES GROUP-->
  <instructionSet group="sampleData">
    <xml action="copy" source="xml/samples/content/documents/events/sample_breakfast.xml" target="/content/documents/{{namespace}}/events/{{dateRepoYearMonth}}"/>
    <xml action="copy" source="xml/samples/content/documents/events/sample_introduction_speech.xml" target="/content/documents/{{namespace}}/events/{{dateRepoYearMonth}}"/>
    <xml action="copy" source="xml/samples/content/documents/events/sample_workshop.xml" target="/content/documents/{{namespace}}/events/{{dateRepoYearMonth}}"/>
    <xml action="copy" source="xml/samples/content/gallery/samples.xml" target="/content/gallery/{{namespace}}"/>
  </instructionSet>
  <!--
    CONFIG DATA
  -->

  <instructionSet>
    <xml action="copy" source="xml/folderoptions/new-events-folder.xml" target="/hippo:configuration/hippo:queries/hippo:templates"/>
    <xml action="copy" source="xml/folderoptions/new-events-document.xml" target="/hippo:configuration/hippo:queries/hippo:templates"/>
  </instructionSet>
  <instructionSet>
    <file action="copy" binary="true" source="icons/new-folder-16.png" target="{{cmsRoot}}/src/main/resources/org/hippoecm/frontend/plugins/standardworkflow/new-events-folder-16.png"/>
  </instructionSet>


</instructions>
