=== bloomreach/brxm/essentials/plugin-sdk/api/src/main/resources/instructions.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
  Copyright 2014-2018 Hippo B.V. (http://www.onehippo.com)

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns="http://www.onehippo.org/essentials/instructions" targetNamespace="http://www.onehippo.org/essentials/instructions">
  <xs:element name="instructions" type="instructionsType"/>

  <!--
    //############################################
    // INSTRUCTION SET
    //############################################
  -->
  <xs:simpleType name="fileActionType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="delete"/>
      <xs:enumeration value="copy"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="xmlActionType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="delete"/>
      <xs:enumeration value="copy"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="directoryActionType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="create"/>
      <xs:enumeration value="copy"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="targetPomType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="project"/>
      <xs:enumeration value="site"/>
      <xs:enumeration value="cms"/>
      <xs:enumeration value="essentials"/>
      <xs:enumeration value="repository-data"/>
      <xs:enumeration value="webfiles"/>
      <xs:enumeration value="application"/>
      <xs:enumeration value="development"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="mavenDependencyScopeType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="compile"/>
      <xs:enumeration value="runtime"/>
      <xs:enumeration value="test"/>
      <xs:enumeration value="system"/>
      <xs:enumeration value="provided"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="instructionsSetType" mixed="true">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element type="fileType" name="file" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element type="freemarkerType" name="freemarker" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element type="directoryType" name="directory" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element type="executeType" name="execute" minOccurs="0" maxOccurs="unbounded"/>
      <!--<xs:element type="placeHoldersType" name="placeholders" minOccurs="0" maxOccurs="unbounded"/>-->
      <xs:element type="xmlType" name="xml" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element type="translationsType" name="translations" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element type="cndType" name="cnd" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element type="hstBeanClassesType" name="hstBeanClasses" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element type="dependencyType" name="mavenDependency" minOccurs="0" maxOccurs="unbounded"/>
    </xs:choice>
    <xs:attribute use="optional" name="group" default="default" type="xs:string"/>
  </xs:complexType>

  <!--
    //############################################
    // SUBTYPES
    //############################################

  -->
  <xs:complexType name="fileType" mixed="true">
    <xs:attribute use="required" name="action" type="fileActionType"/>
    <xs:attribute use="optional" name="source" type="xs:string"/>
    <xs:attribute use="required" name="target" type="xs:string"/>
    <xs:attribute use="optional" name="overwrite" type="xs:boolean" default="false"/>
    <xs:attribute use="optional" name="message" type="xs:string" default="false"/>
    <xs:attribute use="optional" name="binary" type="xs:boolean" default="false"/>
  </xs:complexType>
  <xs:complexType name="freemarkerType" mixed="true">
    <xs:attribute use="required" name="action" type="fileActionType"/>
    <xs:attribute use="optional" name="source" type="xs:string"/>
    <xs:attribute use="required" name="target" type="xs:string"/>
    <xs:attribute use="optional" name="overwrite" type="xs:boolean" default="false"/>
    <xs:attribute use="optional" name="message" type="xs:string" default="false"/>
    <xs:attribute use="optional" name="binary" type="xs:boolean" default="false"/>
  </xs:complexType>
  <xs:complexType name="directoryType" mixed="true">
    <xs:attribute use="required" name="action" type="directoryActionType"/>
    <xs:attribute use="optional" name="source" type="xs:string">
      <xs:annotation>
        <xs:documentation>Source file. We'll first try to check if file exist on a file system and copy it, if not, we'll try to fetch it from the classpath</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute use="required" name="target" type="xs:string"/>
    <xs:attribute use="optional" name="overwrite" type="xs:boolean" default="false"/>
    <xs:attribute use="optional" name="message" type="xs:string" default="false"/>
    <xs:attribute use="optional" name="binary" type="xs:boolean" default="false">
      <xs:annotation>
        <xs:documentation>NOTE: directory cannot have mixed content when executing copy, so either it must contain binaries or text files (because of placeholders)</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  <!-- EXECUTE  -->
  <xs:complexType name="executeType" mixed="true">
    <xs:attribute use="required" name="class" type="xs:string"/>
  </xs:complexType>
  <!-- PLACEHOLDER  -->
  <xs:complexType name="placeHolderType" mixed="true">
    <xs:attribute use="required" name="key" type="xs:string"/>
    <xs:attribute use="required" name="value" type="xs:string"/>
  </xs:complexType>

  <!-- PLACEHOLDERS  -->
  <xs:complexType name="placeHoldersType" mixed="true">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element type="placeHolderType" name="placeholder"/>
    </xs:choice>

  </xs:complexType>

  <xs:complexType name="xmlType" mixed="true">
    <xs:attribute use="required" name="action" type="xmlActionType"/>
    <xs:attribute use="optional" name="source" type="xs:string"/>
    <xs:attribute use="required" name="target" type="xs:string"/>
    <xs:attribute use="optional" name="overwrite" type="xs:boolean" default="false"/>
    <xs:attribute use="optional" name="message" type="xs:string" default="false"/>
  </xs:complexType>
  <xs:complexType name="cndType" mixed="true">
    <xs:attribute use="required" name="documentType" type="xs:string"/>
    <xs:attribute use="required" name="superType" type="xs:string"/>
    <xs:attribute use="optional" name="namespaceUrl" type="xs:string">
      <xs:annotation>
        <!--TODO: NOT IMPLEMENTED YET -->
        <xs:documentation>If not defined essentials template namespace will be used (TODO: NOT IMPLEMENTED YET)</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute use="optional" name="namespacePrefix" type="xs:string">
      <xs:annotation>
        <xs:documentation>If not defined essentials template namespace will be used</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="translationsType" mixed="true">
    <xs:attribute use="required" name="source" type="xs:string"/>
    <xs:attribute use="optional" name="message" type="xs:string" default="false"/>
  </xs:complexType>

  <xs:complexType name="hstBeanClassesType" mixed="true">
    <xs:attribute use="required" name="pattern" type="xs:string">
      <xs:annotation>
        <xs:documentation>Pattern for classpath scanning of annotated HST bean classes, e.g. 'classpath*:org/example/**/*.class'.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute use="optional" name="message" type="xs:string" default="false"/>
  </xs:complexType>

  <xs:complexType name="dependencyType" mixed="true">
    <xs:attribute use="required" name="targetPom" type="targetPomType"/>
    <xs:attribute use="required" name="groupId" type="xs:string"/>
    <xs:attribute use="required" name="artifactId" type="xs:string"/>
    <xs:attribute use="optional" name="version" type="xs:string"/>
    <xs:attribute use="optional" name="scope" type="mavenDependencyScopeType"/>
    <xs:attribute use="optional" name="type" type="xs:string"/>
    <xs:attribute use="optional" name="message" type="xs:string" default="false"/>
  </xs:complexType>

  <!--  <xs:complexType name="instructionsSet" mixed="true">
      <xs:attribute use="required" name="action" type="fileActionType" default="copy"/>
      <xs:attribute use="optional" name="source" type="xs:string"/>
      <xs:attribute use="optional" name="target" type="xs:string"/>
      <xs:attribute use="optional" name="overwrite" type="xs:boolean" default="false"/>
    </xs:complexType>-->

  <!--
    //############################################
    // MAIN TYPE
    //############################################
  -->
  <xs:complexType name="instructionsType">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element type="instructionsSetType" name="instructionSet"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== bloomreach/brxm/essentials/plugins/urlrewriter/src/main/resources/META-INF/urlrewriter_plugin_instructions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright 2017-2018 Hippo B.V. (http://www.onehippo.com)

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  -->
<instructions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.onehippo.org/essentials/instructions /instructions.xsd"
              xmlns="http://www.onehippo.org/essentials/instructions">
  <instructionSet>
    <mavenDependency targetPom="cms-dependencies" groupId="com.onehippo.cms7" artifactId="hippo-addon-urlrewriter-module-cms"/>
    <mavenDependency targetPom="cms-dependencies" groupId="com.onehippo.cms7" artifactId="hippo-addon-urlrewriter-module-repository"/>
    <mavenDependency targetPom="site-components" groupId="com.onehippo.cms7" artifactId="hippo-addon-urlrewriter-module-hst"/>
    <hstBeanClasses pattern="classpath*:org/onehippo/forge/**/*.class" />
    <execute class="com.onehippo.cms7.essentials.plugins.urlrewriter.UrlRewriterInstruction" />
    <file action="copy" source="instructions/xml/spring/urlrewriter-context.xml" target="{{siteResources}}/META-INF/hst-assembly/overrides/urlrewriter-context.xml"/>
  </instructionSet>

  <instructionSet group="sampleData">
    <file action="copy" source="instructions/yaml/sample-rewriter-rules.yaml" target="{{developmentContent}}/essentials/urlrewriter/sample-rewriter-rules.yaml"/>
  </instructionSet>
</instructions>
